import { mkdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { LANGUAGES } from '../catalog/index.js';
import type { LanguageSpec } from '../catalog/types.js';
import type { DetectedLanguage } from '../detect.js';
import { PRESET_RIGHTHOOK_DIR, renderLefthook } from '../generate/lefthook.js';
import { COVERAGE_GATE_PY, MERGE_CONFLICTS_SH, RUN_SH } from '../generate/runSh.js';
import { renderReusable } from '../generate/workflows.js';
import { allToolsFor } from '../variants.js';

const require = createRequire(import.meta.url);

/**
 * Preset emitter.
 *
 * Runs as the second half of `npm run build`, and again from `righthook
 * presets`. It renders from the same generators the CLI uses, so the shipped
 * presets cannot drift from what `righthook init` writes.
 *
 * Why presets exist at all: lefthook resolves `extends` paths against the *git
 * root*, not the including file (verified in
 * `review/lefthook/internal/config/loader.go`, `extendRecursive`). Recursively
 * extending fragments out of `node_modules` therefore needs hand-written
 * `node_modules/<pkg>/...` paths and a "never extend a preset and its own
 * fragment" discipline. A single self-contained preset file sidesteps that
 * entire class of bug — which is exactly why the default delivery mode
 * generates one file instead of extending anything.
 */

/** Every language, with its first variant and every conditional tool. */
export function fullMatrix(): DetectedLanguage[] {
  return LANGUAGES.map((language: LanguageSpec) => ({
    language,
    markers: language.detect.length > 0 ? language.detect : ['always'],
    variant: language.variants?.[0]?.id,
    tools: allToolsFor(language),
  }));
}

/** The universal hooks plus the first language that contributes hook commands. */
function minimalMatrix(): DetectedLanguage[] {
  const universal = LANGUAGES.find((language) => language.id === 'universal')!;
  const firstWithHooks = LANGUAGES.find(
    (language) => language.id !== 'universal' && language.tools.length > 0,
  )!;
  return [
    { language: universal, markers: ['always'], tools: allToolsFor(universal) },
    {
      language: firstWithHooks,
      markers: firstWithHooks.detect,
      variant: firstWithHooks.variants?.[0]?.id,
      tools: allToolsFor(firstWithHooks),
    },
  ];
}

function header(title: string, body: string): string {
  return [
    `# ${title}`,
    '#',
    '# Generated by righthook from the same generators the CLI uses.',
    '#',
    '# `extends` in lefthook resolves paths against the GIT ROOT, not the file',
    '# that lists them (internal/config/loader.go, extendRecursive). Each preset',
    '# is therefore one self-contained document: extend one of them, and do not',
    '# also extend anything it contains.',
    '',
    body,
  ].join('\n');
}

/** The reusable `workflow_call` pipeline, rendered from the full matrix. */
export function renderReusableWorkflow(version: string): string {
  return renderReusable(fullMatrix(), version);
}

/** Every shipped preset, keyed by its repo-root-relative path. */
export function renderPresets(version: string): Map<string, string> {
  const files = new Map<string, string>();
  const matrix = fullMatrix();
  const reusable = renderReusableWorkflow(version);

  files.set(
    'presets/lefthook.all.yml',
    header(
      'righthook: every language in the matrix',
      renderLefthook(matrix, { version, righthookDir: PRESET_RIGHTHOOK_DIR }),
    ),
  );
  files.set(
    'presets/lefthook-minimal.yml',
    header(
      'righthook: universal hooks plus one language',
      renderLefthook(minimalMatrix(), {
        version,
        righthookDir: PRESET_RIGHTHOOK_DIR,
      }),
    ),
  );
  // The reusable workflow lives at the package root, because that is the path
  // a consumer writes in `uses:` — `owner/righthook/.github/workflows/ci.yml@v1`.
  files.set('workflows/ci.yml', reusable);
  files.set('presets/workflows/ci.yml', reusable);
  return files;
}

/**
 * The `righthook presets` output: every preset preceded by its path, so a
 * consumer can see exactly what extending righthook would pull in.
 */
export function generate(version: string): string {
  const sections: string[] = [];
  for (const [rel, content] of renderPresets(version)) {
    sections.push(`# ===== ${rel} =====`);
    sections.push(content);
  }
  return `${sections.join('\n')}\n`;
}

/**
 * Write the presets, the reusable workflow and the launcher scripts into the
 * package tree. Called by `npm run build`.
 *
 * The package repository's own `.github/workflows/ci.yml` is a byte-identical
 * copy of `workflows/ci.yml`, so a consumer's `uses:` path resolves and the
 * reusable definition cannot drift from what is published.
 */
export function writePresets(version: string, packageRoot: string): string[] {
  const files = renderPresets(version);
  const written: string[] = [];

  for (const [rel, content] of files) {
    const abs = path.join(packageRoot, rel);
    mkdirSync(path.dirname(abs), { recursive: true });
    writeFileSync(abs, content, 'utf8');
    written.push(rel);
  }

  const ownWorkflow = path.join(packageRoot, '.github/workflows/ci.yml');
  mkdirSync(path.dirname(ownWorkflow), { recursive: true });
  writeFileSync(ownWorkflow, files.get('workflows/ci.yml')!, 'utf8');
  written.push('.github/workflows/ci.yml');

  // This repository's own `.github/workflows/righthook.yml` is written by
  // `righthook init`, not here: it must advertise the languages this repository
  // actually has, which is a detection result, and detection is the CLI's job.

  // Ship the launcher scripts and the coverage gate so the presets and the
  // reusable workflow are functional on their own: preset `run:` lines point
  // at `node_modules/righthook/.righthook/*`, and the reusable workflow's gate
  // step invokes both the consumer's and this copy.
  for (const [rel, content] of [
    ['.righthook/run.sh', RUN_SH] as const,
    ['.righthook/merge-conflicts.sh', MERGE_CONFLICTS_SH] as const,
    ['.righthook/coverage_gate.py', COVERAGE_GATE_PY] as const,
  ]) {
    const abs = path.join(packageRoot, rel);
    mkdirSync(path.dirname(abs), { recursive: true });
    writeFileSync(abs, content, { encoding: 'utf8', mode: 0o755 });
    written.push(rel);
  }

  return written;
}

// Executed as `node dist/scripts/emit-presets.js` during `build`. The
// package.json lookup stays inside this block: importing this module for its
// generators must not depend on the caller's directory layout.
if (fileURLToPath(import.meta.url) === path.resolve(process.argv[1] ?? '')) {
  const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
  const pkg = require(path.join(packageRoot, 'package.json')) as {
    version: string;
  };
  const written = writePresets(pkg.version, packageRoot);
  process.stdout.write(`presets: ${written.join(', ')}\n`);
}
