import type { DetectedLanguage } from '../detect.js';

/**
 * Auxiliary managed files: configs that the generated hooks reference.
 *
 * righthook emits hooks, not tool configuration. These five files exist only
 * because a generated command names them on its command line, so they must
 * exist for the command not to fail on a fresh clone.
 */

export const EDITORCONFIG = `# Generated by righthook.
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true
indent_style = space
indent_size = 2

[*.{py,pyi}]
indent_size = 4

[Makefile]
indent_style = tab

[*.go]
indent_style = tab
`;

export const COMMITLINT_CONFIG = `// Generated by righthook.
export default { extends: ['@commitlint/config-conventional'] };
`;

export const JSCPD_CONFIG = `${JSON.stringify(
  {
    threshold: 5,
    'min-tokens': 70,
    reporters: ['console'],
    ignore: [
      '**/node_modules/**',
      '**/vendor/**',
      '**/target/**',
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
    ],
  },
  null,
  2,
)}\n`;

export const YAMLLINT_CONFIG = `# Generated by righthook.
extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
`;

export const OSV_SCANNER_CONFIG = `# Generated by righthook.
# Add exceptions as [[IgnoredVulns]] tables:
#   [[IgnoredVulns]]
#   id = "GHSA-xxxx-xxxx-xxxx"
#   reason = "why this is not exploitable here"
`;

export const GITLEAKS_PLACEHOLDER = `# Generated by righthook. betterleaks falls back to .gitleaks.toml when present.
`;

/** Dependabot ecosystem slugs by detected language id. */
export const DEPENDABOT_BY_LANGUAGE: Record<string, string[]> = {
  universal: ['github-actions'],
  typescript: ['npm'],
  python: ['pip'],
  go: ['gomod'],
  rust: ['cargo'],
  ruby: ['bundler'],
  php: ['composer'],
  java: ['maven', 'gradle'],
  kotlin: ['gradle'],
  dotnet: ['nuget'],
  swift: ['swift'],
  dart: ['pub'],
  docker: ['docker'],
};

/**
 * `.github/dependabot.yml` for the detected ecosystems.
 *
 * Each ecosystem gets a weekly schedule and one `minor-and-patch` group, so a
 * week of patch bumps arrives as a single reviewable PR.
 */
export function renderDependabot(detected: DetectedLanguage[]): string {
  const ecosystems: string[] = [];
  for (const entry of detected) {
    for (const slug of entry.language.dependabot ?? DEPENDABOT_BY_LANGUAGE[entry.language.id] ?? []) {
      if (!ecosystems.includes(slug)) ecosystems.push(slug);
    }
  }
  ecosystems.sort();

  const lines: string[] = ['# Generated by righthook.', 'version: 2', 'updates:'];
  for (const slug of ecosystems) {
    lines.push(`  - package-ecosystem: ${slug}`);
    lines.push('    directory: "/"');
    lines.push('    schedule:');
    lines.push('      interval: weekly');
    lines.push('    open-pull-requests-limit: 5');
    lines.push('    groups:');
    lines.push('      minor-and-patch:');
    lines.push('        patterns:');
    lines.push('          - "*"');
    lines.push('        update-types:');
    lines.push('          - minor');
    lines.push('          - patch');
  }
  lines.push('');
  return lines.join('\n');
}

/** Does the detected set include Ruby? */
export function hasRuby(detected: DetectedLanguage[]): boolean {
  return detected.some((entry) => entry.language.id === 'ruby');
}
