/**
 * The `.righthook/` helper scripts.
 *
 * These are shipped as string templates rather than files so the built
 * package is a single `dist/` tree with no asset-copying step. Each string is
 * written byte-for-byte to the target repository.
 */

/**
 * `.righthook/run.sh` — resolve a tool or skip it locally.
 *
 * The skip-exit-0 semantics are the whole point: a missing local tool must not
 * block a commit, because CI runs the same check unguarded and is the gate. A
 * bug here (e.g. exiting non-zero on a missing tool) would make the package
 * unusable; a bug that exits 0 on a *failing* tool would silently bypass every
 * check, which is why `exec` is used and the tool's own status propagates.
 */
export const RUN_SH = `#!/bin/sh
# Generated by righthook. Resolves a tool, or skips it locally.
# CI runs the same checks without this launcher, so a missing local tool is not a bypass.
set -u
if [ "$#" -eq 0 ]; then
  echo "righthook: run.sh requires a tool name" >&2
  exit 2
fi
tool=$1
shift
bin=$tool
case "$tool" in
  */*) : ;;
  *)
    if [ -x "node_modules/.bin/$tool" ]; then
      bin="node_modules/.bin/$tool"
    elif ! command -v "$tool" >/dev/null 2>&1; then
      echo "righthook: $tool not installed - skipped locally (enforced in CI)"
      exit 0
    fi
    ;;
esac
if [ ! -x "$bin" ] && ! command -v "$bin" >/dev/null 2>&1; then
  echo "righthook: $bin not found - skipped locally (enforced in CI)"
  exit 0
fi
exec "$bin" "$@"
`;

/**
 * `.righthook/merge-conflicts.sh` — fail when a file has conflict markers.
 *
 * Exists because lefthook shell-escapes `{staged_files}` *after* the command
 * string is assembled, so an inline `sh -c 'for f in {staged_files}; ...'`
 * receives a mangled list and dies with `syntax error: unexpected end of
 * file`. As a script the file list arrives as ordinary positional arguments.
 */
export const MERGE_CONFLICTS_SH = `#!/bin/sh
# Generated by righthook. Fails when any listed file contains a conflict marker.
set -u
status=0
for f in "$@"; do
  [ -f "$f" ] || continue
  if grep -nE '^(<<<<<<<|>>>>>>>|=======)' "$f"; then
    status=1
  fi
done
if [ "$status" -ne 0 ]; then
  echo "righthook: merge conflict markers found in staged files" >&2
fi
exit "$status"
`;

/**
 * `.righthook/coverage_gate.py` — parse coverage artifacts and enforce a
 * total-coverage threshold.
 *
 * Exits 2, never 0, when no report could be parsed: a silent pass after every
 * producing tool was skipped would be a bypass of the gate.
 */
export const COVERAGE_GATE_PY = `"""Generated by righthook. Enforces a total-coverage threshold over mixed reports.

usage:
  coverage_gate.py --threshold <pct> [--report <name>=<path> ...] [--min-lines <n>]

Supported report formats (sniffed by content, not by extension):
  * Cobertura XML  - root <coverage line-rate="...">
  * JaCoCo XML     - root <report> with <counter type="LINE" missed covered>
  * lcov           - LF:/LH: records

The aggregate is sum(LH) / sum(LF) across every parsed report, so a language
with more lines dominates as it should. Exits 2 when nothing parsed.
"""

import argparse
import os
import re
import sys
import xml.etree.ElementTree as ET

FAIL = 1
NO_DATA = 2


def parse_cobertura(path):
    root = ET.parse(path).getroot()
    line_rate = root.get("line-rate")
    if line_rate is None:
        return None
    missed = int(root.get("lines-missed", "0") or 0)
    covered = int(root.get("lines-covered", "0") or 0)
    if missed + covered == 0:
        # Derive counts from the rate when the explicit counts are absent.
        lines_valid = int(root.get("lines-valid", "0") or 0)
        if lines_valid == 0:
            return None
        covered = int(round(float(line_rate) * lines_valid))
        missed = lines_valid - covered
    return (covered, covered + missed)


def parse_jacoco(path):
    root = ET.parse(path).getroot()
    if root.tag != "report":
        return None
    for counter in root.findall("counter"):
        if counter.get("type") == "LINE":
            missed = int(counter.get("missed", "0") or 0)
            covered = int(counter.get("covered", "0") or 0)
            return (covered, missed + covered)
    return None


def parse_lcov(path):
    covered = 0
    total = 0
    found = False
    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            if line.startswith("LF:"):
                total += int(line[3:].strip() or 0)
                found = True
            elif line.startswith("LH:"):
                covered += int(line[3:].strip() or 0)
                found = True
    if not found:
        return None
    return (covered, total)


def sniff(path):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            head = handle.read(4096)
    except OSError:
        return None
    if re.search(r"<coverage\\b", head):
        try:
            return parse_cobertura(path)
        except (ET.ParseError, ValueError):
            return None
    if re.search(r"<report\\b", head):
        try:
            return parse_jacoco(path)
        except (ET.ParseError, ValueError):
            return None
    if re.search(r"^(SF|LF|LH):", head, re.MULTILINE):
        try:
            return parse_lcov(path)
        except (OSError, ValueError):
            return None
    return None


def main(argv=None):
    parser = argparse.ArgumentParser(description="righthook coverage gate")
    parser.add_argument("--threshold", type=float, required=True)
    parser.add_argument("--report", action="append", default=[])
    parser.add_argument("--min-lines", type=int, default=1)
    args = parser.parse_args(argv)

    rows = []
    total_covered = 0
    total_lines = 0
    parsed_any = False

    for spec in args.report:
        if "=" not in spec:
            print("SKIP %s: malformed --report (expected name=path)" % spec)
            continue
        name, _, path = spec.partition("=")
        if not os.path.exists(path):
            print("SKIP %s: no coverage data (missing %s)" % (name, path))
            continue
        counts = sniff(path)
        if counts is None:
            print("SKIP %s: no coverage data (unrecognised %s)" % (name, path))
            continue
        covered, lines = counts
        if lines < args.min_lines:
            print("SKIP %s: no coverage data (%d lines < %d)" % (name, lines, args.min_lines))
            continue
        parsed_any = True
        total_covered += covered
        total_lines += lines
        rows.append((name, lines, covered, (covered / lines * 100.0) if lines else 0.0))

    if rows:
        width = max(len(row[0]) for row in rows)
        print("%-*s  %8s  %8s  %7s" % (width, "LANG", "LINES", "COVERED", "PCT"))
        for name, lines, covered, pct in rows:
            print("%-*s  %8d  %8d  %6.2f%%" % (width, name, lines, covered, pct))

    if not parsed_any:
        print("righthook: no coverage data was found; failing rather than passing silently")
        return NO_DATA

    aggregate = total_covered / total_lines * 100.0
    label = "%.2f%%" % aggregate
    if aggregate < args.threshold:
        print("FAIL: total coverage %s < %g%%" % (label, args.threshold))
        return FAIL
    print("OK: total coverage %s >= %g%%" % (label, args.threshold))
    return 0


if __name__ == "__main__":
    sys.exit(main())
`;

/**
 * `.righthook/simplecov.rb` — coverage formatter for Ruby.
 *
 * Requires `simplecov-cobertura` when it resolves; otherwise leaves
 * SimpleCov's default formatter in place and the gate reports Ruby as SKIP.
 */
export const SIMPLECOV_RB = `# Generated by righthook. Loaded via RUBYOPT in CI only.
require 'simplecov'

formatter =
  begin
    require 'simplecov-cobertura'
    SimpleCov::Formatter::CoberturaFormatter
  rescue LoadError
    # Without simplecov-cobertura there is no Cobertura artifact; the CI gate
    # then reports Ruby as SKIP rather than enforcing a threshold it cannot see.
    SimpleCov::Formatter::JSONFormatter
  end

SimpleCov.start do
  minimum_coverage 0
  formatter formatter
end
`;
