"""Generated by righthook. Enforces a total-coverage threshold over mixed reports.

usage:
  coverage_gate.py --threshold <pct> [--report <name>=<path> ...] [--min-lines <n>]

Supported report formats (sniffed by content, not by extension):
  * Cobertura XML  - root <coverage line-rate="...">
  * JaCoCo XML     - root <report> with <counter type="LINE" missed covered>
  * lcov           - LF:/LH: records

The aggregate is sum(LH) / sum(LF) across every parsed report, so a language
with more lines dominates as it should. Exits 2 when nothing parsed.
"""

import argparse
import os
import re
import sys
import xml.etree.ElementTree as ET

FAIL = 1
NO_DATA = 2


def parse_cobertura(path):
    root = ET.parse(path).getroot()
    line_rate = root.get("line-rate")
    if line_rate is None:
        return None
    missed = int(root.get("lines-missed", "0") or 0)
    covered = int(root.get("lines-covered", "0") or 0)
    if missed + covered == 0:
        # Derive counts from the rate when the explicit counts are absent.
        lines_valid = int(root.get("lines-valid", "0") or 0)
        if lines_valid == 0:
            return None
        covered = int(round(float(line_rate) * lines_valid))
        missed = lines_valid - covered
    return (covered, covered + missed)


def parse_jacoco(path):
    root = ET.parse(path).getroot()
    if root.tag != "report":
        return None
    for counter in root.findall("counter"):
        if counter.get("type") == "LINE":
            missed = int(counter.get("missed", "0") or 0)
            covered = int(counter.get("covered", "0") or 0)
            return (covered, missed + covered)
    return None


def parse_lcov(path):
    covered = 0
    total = 0
    found = False
    with open(path, "r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            if line.startswith("LF:"):
                total += int(line[3:].strip() or 0)
                found = True
            elif line.startswith("LH:"):
                covered += int(line[3:].strip() or 0)
                found = True
    if not found:
        return None
    return (covered, total)


def sniff(path):
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            head = handle.read(4096)
    except OSError:
        return None
    if re.search(r"<coverage\b", head):
        try:
            return parse_cobertura(path)
        except (ET.ParseError, ValueError):
            return None
    if re.search(r"<report\b", head):
        try:
            return parse_jacoco(path)
        except (ET.ParseError, ValueError):
            return None
    if re.search(r"^(SF|LF|LH):", head, re.MULTILINE):
        try:
            return parse_lcov(path)
        except (OSError, ValueError):
            return None
    return None


def main(argv=None):
    parser = argparse.ArgumentParser(description="righthook coverage gate")
    parser.add_argument("--threshold", type=float, required=True)
    parser.add_argument("--report", action="append", default=[])
    parser.add_argument("--min-lines", type=int, default=1)
    args = parser.parse_args(argv)

    rows = []
    total_covered = 0
    total_lines = 0
    parsed_any = False

    for spec in args.report:
        if "=" not in spec:
            print("SKIP %s: malformed --report (expected name=path)" % spec)
            continue
        name, _, path = spec.partition("=")
        if not os.path.exists(path):
            print("SKIP %s: no coverage data (missing %s)" % (name, path))
            continue
        counts = sniff(path)
        if counts is None:
            print("SKIP %s: no coverage data (unrecognised %s)" % (name, path))
            continue
        covered, lines = counts
        if lines < args.min_lines:
            print("SKIP %s: no coverage data (%d lines < %d)" % (name, lines, args.min_lines))
            continue
        parsed_any = True
        total_covered += covered
        total_lines += lines
        rows.append((name, lines, covered, (covered / lines * 100.0) if lines else 0.0))

    if rows:
        width = max(len(row[0]) for row in rows)
        print("%-*s  %8s  %8s  %7s" % (width, "LANG", "LINES", "COVERED", "PCT"))
        for name, lines, covered, pct in rows:
            print("%-*s  %8d  %8d  %6.2f%%" % (width, name, lines, covered, pct))

    if not parsed_any:
        print("righthook: no coverage data was found; failing rather than passing silently")
        return NO_DATA

    aggregate = total_covered / total_lines * 100.0
    label = "%.2f%%" % aggregate
    if aggregate < args.threshold:
        print("FAIL: total coverage %s < %g%%" % (label, args.threshold))
        return FAIL
    print("OK: total coverage %s >= %g%%" % (label, args.threshold))
    return 0


if __name__ == "__main__":
    sys.exit(main())
