#!/bin/sh
# Generated by righthook. Fails when any listed file contains a conflict marker.
set -u
status=0
for f in "$@"; do
  [ -f "$f" ] || continue
  if grep -nE '^(<<<<<<<|>>>>>>>|=======)' "$f"; then
    status=1
  fi
done
if [ "$status" -ne 0 ]; then
  echo "righthook: merge conflict markers found in staged files" >&2
fi
exit "$status"
