#!/bin/sh
# Generated by righthook. Resolves a tool, or skips it locally.
# CI runs the same checks without this launcher, so a missing local tool is not a bypass.
set -u
if [ "$#" -eq 0 ]; then
  echo "righthook: run.sh requires a tool name" >&2
  exit 2
fi
tool=$1
shift
bin=$tool
case "$tool" in
  */*) : ;;
  *)
    if [ -x "node_modules/.bin/$tool" ]; then
      bin="node_modules/.bin/$tool"
    elif ! command -v "$tool" >/dev/null 2>&1; then
      echo "righthook: $tool not installed - skipped locally (enforced in CI)"
      exit 0
    fi
    ;;
esac
if [ ! -x "$bin" ] && ! command -v "$bin" >/dev/null 2>&1; then
  echo "righthook: $bin not found - skipped locally (enforced in CI)"
  exit 0
fi
exec "$bin" "$@"
